### PR TITLE
Bootstrap4

### PR DESCRIPTION
**Pull request by keeganmcbride**
This PR updates JKAN from Bootstrap 3 to Bootstrap 4 (I think). It is also updates all the NPM libraries needed. I think everything should be working, but I did not get a chance to try out the admin functionality at all.

### CODE REVIEW

**Comment by timwis** [comment]
Thanks again for putting in this work! I've deployed this PR to: https://jkan-bs4.surge.sh/
Below are a few minor issues I noticed. But overall it looks really close!

1. The category icons seem to be aligned to the left now, rather than centred. Any idea why?
2. The breadcrumbs on [`/admin/`](https://jkan-bs4.surge.sh/admin/) don't seem to have formatting anymore.
3. There used to be a well on the the "Categories" page of `/admin/` (see [live demo](https://demo.jkan.io/admin/) for example). Are those gone in bootstrap 4? (Also on the licenses page, and on the resources section of editing a dataset)
4. It looks like the theme URLs have updated. Should we update the thumbnails or links on the "Themes" page of `/admin/`?
5. When [editing an organisation](https://jkan-bs4.surge.sh/organizations/city-planning-commission-pcpc/?view=edit), it looks like the list of its datasets still shows at the top. This didn't happen on the [current demo site](https://demo.jkan.io/organizations/city-planning-commission-pcpc/?view=edit) - I wonder what could have caused that? This also happens when [editing a dataset](https://jkan-bs4.surge.sh/datasets/311-service-requests/?view=edit)

**Comment by keeganmcbride** [comment]
Points 1,2,3 should all be done now. We can go ahead and update the Images for 4, sure, no problem. For 5 I am still trying to figure out what is going on here, the bug is not clear to me right now.

**Comment by keeganmcbride** [comment]
The thing with (5) is related to using the d-flex class for the row and how it works with the CSS from the view-switcher. If you just use a normal row then everything works as it should, but the layout for the page is a bit weird.

**Comment by keeganmcbride** [comment]
@timwis All issues should be resolved now, but sorry for the mess that this commit is...

**Comment by timwis** [comment]
This looks great @keeganmcbride, thanks for all your hard work on it. Everything looks good, but just curious why there are a couple inline styles like `style = "float: right;"` rather than bootstrap classes?

**Comment by keeganmcbride** [comment]
@timwis I tried to do just with bootstrap, but it seems that there was some issues with the JS overwriting these and so this was a way to fix it without me fiddling with the JS :S

**Comment by timwis** [comment]
I was just comparing the current version and this one side by side, and the only discrepancies I saw are rather minor:

- navbar menu icon missing on mobile
- dataset page: the organisation column becomes too narrow on medium screens (not sure how this was prevented before, maybe min-width?)
- datasets list and organisation page: padding around list/search was reduced
- homepage category icons are laid out differently, though i can't imagine this matters

If any quick fixes come to mind let me know, otherwise I'll spend a few mins trying to figure out the first 3.

**Comment by keeganmcbride** [comment]
I think it makes more sense for you to tackle them if you're already planning on it. I can jump in if you have a question though.

**Comment by timwis** [comment]
Okay I've fixed everything except the issue with the navbar, which I assume is just a new navbar layout with bootstrap 4. The javascript shouldn't affect it -- it just looks for the `data-hook` elements. Can you take a look at that and verify it works when logged in too?

**Comment by keeganmcbride** [comment]
Sure, let me look.

**Comment by patcon** [comment]
This good to merge? Just noticed that it stalled out seemingly right when it was done :)

**Pull request merged**
