### PR TITLE
Components

### LINKED ISSUE #66: Use growl-style alerts
If user is scrolled down, they don't see the alerts at the top. A library like [toastr](https://github.com/CodeSeven/toastr) may be a better alternative.

### LINKED ISSUE #78: Component-based JavaScript architecture
Per a suggestion from @themightychris, rather than initializing javascript functionality based on the current URL (via a router), detect components on the page via a `data-component` attribute on dom elements, and activate the functionality of the components, sharing global resources such as data and events where applicable.

This would also more easily allow component reuse. A significant refactor, and not pressing, but sounds worthwhile.

### LINKED ISSUE #85: Remove setup page from JKAN core
Now that it's covered in the JKAN website per #55, it's no longer needed in the core JKAN codebase.

### PR DESCRIPTION
**Pull request by timwis**
This pull request involves a complete refactor of the javascript architecture. Previously, JKAN used a router-like configuration to determine page page it was on, and then executed logic for that particular page. Now JKAN looks for a list of components on any page and initializes each component class (see `index.js`), passing it its container element and any shared global variables. Components are configured through `data-xxx=""` attributes on the element (where configuration is necessary). This allows components to be reused on any page.

My hope is that this is easier to dive into and more reusable. Thoughts @pezholio @themightychris?

Might be easier to view by looking at [the branch](https://github.com/timwis/jkan/tree/components/scripts/src).

EDIT: I've also documented it on the [Architecture](https://github.com/timwis/jkan/wiki/Architecture#javascript) wiki page.

Closes #78 and closes #85 and closes #66

### CODE REVIEW

**Comment by pezholio** [comment]
Ah, smart. Also makes things a lot more DRY too. I think I might've struggled with this a bit more initially - JS isn't my first language, and I think the MVC-ish nature of the router approach meant it made sense to me. That said, if this was documented, I'd be able to dive into this easily :+1:

**Comment by timwis** [comment]
Thanks @pezholio - I just took a stab at documenting it [in the wiki](https://github.com/timwis/jkan/wiki/Architecture).

**Comment by timwis** [comment]
Pinging @JJediny @abhinemani @Floppy as other folks who've dove into JKAN's code base. Do you also feel this makes sense? Any reason not to merge?

**Comment by themightychris** [comment]
Some docs outlining what the runtime flow is and how a developer would find where the code for something is and how to add components would be a great help, reading the code only have me a partial fuzzy picture of it. I wouldn't hold off merging for that though it's not a regression over what was before

**Comment by timwis** [comment]
@themightychris did you see this?
https://github.com/timwis/jkan/wiki/Architecture

**Comment by themightychris** [comment]
I did not, that's perfect! (and as a side note I'm a proponent of versioning docs alongside the code they document so it's never fuzzy what versions of docs and code go together)

**Comment by JJediny** [comment]
After taking a look at the file changes/wiki/thread i see no reason not to pull. The more adstracted the JS is from Jekyll the easier it will be to reuse components else where so +1...

Without knowing the full effect, is there any functionality lost?

**Comment by timwis** [comment]
Thanks for the feedback guys. and @JJediny nope, no functionality lost.

**Pull request merged**
