### PR TITLE
Add docker compose option and switch CI from Travis to GH Actions

### PR DESCRIPTION
**Pull request by BryanQuigley**
- Add Github Super linter for some basic linting
 - Add docker compose to be able to start running jekyll on any host
 - Add scripts/lint so that you can run Super Linter locally.
 - Update README for install bits today and docker compose instructions

The Travis build has htmlproofing which we might want to look into re-adding in the future -but it's not working today.

### CODE REVIEW

**Comment by BryanQuigley** [comment]
@JackGilmore would you be interested in reviewing this PR?

**Comment by JackGilmore** [comment]
@BryanQuigley I don't have collaborator permissions to approve and merge but I'm happy to look through this. 

Do you have any pointers for testing or should it just be as simple as running the docker compose command?

**Comment by BryanQuigley** [comment]
Thanks!  I've got write access - but still want to get someone to review it if it's a good direction to go in and for mistakes.

Really just running the docker compose command should be it.  Make sure it acts as you would expect for development.

**Comment by JackGilmore** [comment]
Ran it and it works fine. I see gatekeeper also has a [dockerfile](https://github.com/prose/gatekeeper#run-using-docker). Wonder if it's worth trying to include that in the compose file too?

Happy for this to get merged as a version 1 though and we could always open a new issue for adding gatekeeper

**Comment by BryanQuigley** [comment]
Thanks for the review!  We can definitely consider that - but with Heroku dropping the free plan, I was also wondering if it makes sense to look at dropping the login on the site - opened #193  for that.

**Pull request merged**
