### PR TITLE
Gh pages

### PR DESCRIPTION
**Pull request by Donymuslimin**

### CODE REVIEW

**Comment by timwis** [comment]
Hi @Donymuslimin, it looks like you may have created this pull request accidentally, so I'll close it out. Let me know if you've run into any trouble.

**Comment by Donymuslimin** [comment]
Sorry for that.

I have trouble with pull request.


Dikirim dari Outlook Mobile






On Wed, Apr 27, 2016 at 2:31 PM -0700, "Tim Wisniewski" <notifications@github.com> wrote:





Closed #111.

---
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub:
https://github.com/timwis/jkan/pull/111#event-643526330

**Comment by timwis** [comment]
No worries -- are you trying to submit a feature? Or are you trying to update your fork?

**Comment by Donymuslimin** [comment]
No, i dont think to submit featured


Im trying to update the files of my fork

But when im updates this files, i dont know it linked into master from your script.

Im new to github sorry.




Dikirim dari Outlook Mobile






On Wed, Apr 27, 2016 at 2:38 PM -0700, "Tim Wisniewski" <notifications@github.com> wrote:





No worries -- are you trying to submit a feature? Or are you trying to update your fork?

---

**Comment by timwis** [comment]
Oh, no worries!

**Pull request closed without merging**
