### PR TITLE
Drop javascript from footer and add to only the pages it's needed on

### PR DESCRIPTION
**Pull request by BryanQuigley**
The goal is to make it easier to restructure/reduce javascript in the future if we only need to test the 3 pages it acts on.

### CODE REVIEW

**Comment by BryanQuigley** [comment]
My goal was actually just to make it easier to identify the places that use javascript so if we want to change off of jquery/lodash in the future it's easier/more obvious where we need to test.

I'm totally missing the bootstrap js or navbar differences from my build (or my ability to see it). Will revisit after I take a closer look.

**Comment by timwis** [comment]
Ah, okay. In that case, I wonder if [this search](https://github.com/search?q=repo%3Atimwis%2Fjkan+data-component+language%3AHTML&type=code&l=HTML) would make it even easier to see what to test?

**Comment by BryanQuigley** [comment]
Yes, but I still don't see the navigation javascript code being actually used. What does it do?

**Comment by timwis** [comment]
> Yes, but I still don't see the navigation javascript code being actually used. What does it do?

Sorry for the delay! [`index.js`](https://github.com/timwis/jkan/blob/main/scripts/src/index.js#L4) imports [bootstrap.native](https://thednp.github.io/bootstrap.native/), a JS library that reimplements the interactive functionality of bootstrap in vanilla JS (otherwise it would be jQuery). We only pull in the 'collapse' feature, which we use in [the header](https://github.com/timwis/jkan/blob/main/_includes/header.html#L4) on every page, to enable the navbar to expand/collapse on small screens. It doesn't look like that feature is working on OpenDataPhilly.org (try on mobile or narrow browser window), but it should work normally.

**Comment by BryanQuigley** [comment]
Thanks!  Wow - not sure how I missed that it was broken.  May revisit this, but for now let's close it out.

**Pull request closed without merging**
