### PR TITLE
Use parcel for JS bundling

### LINKED ISSUE #219: Simplify JS compliation
Our JS is simple enough that we don't need a fancy webpack configuration. We should switch to something easier to maintain and use. Whether that's the latest webpack with the default configuration, or something like parcel, esbuild, etc.

### PR DESCRIPTION
**Pull request by timwis**
Closes #219

### CODE REVIEW

**Review by lydiascarf — COMMENTED** [review]
When I run `docker compose up` on this branch, I get 5k+ files in the `vendor` directory! Also, when I run `npm install` on host, I get updates to the package lock. I assume the vendor stuff should be gitignored and the package lock update should be included in this PR.

Could you please outline a couple test instructions as well? I ran `npm run build`, then added and ran a dev script like so to the `package.json`:
```
    "dev": "parcel scripts/src/index.js --dist-dir scripts/dist"
```
But when I then navigated to http://localhost:1234/, I only got 404s.

**Comment by timwis** [comment]
Hi @lydiascarf, thanks for testing this! 

Regarding the `vendor` directory, good catch—I haven't been using docker in development, and my guess is @BryanQuigley may have `vendor` in his global `.gitignore` or something. I agree that should be added to the repo's `.gitignore` file (in a separate PR).

As for the 5,000 files, the good news is that has nothing to do with parcel. It looks like that's just how caching worked in the `jekyll/jekyll:3.9.2` image, and it's been fixed in the latest image. I created this branch a few days before #236 was merged, so you would have been using the old image version when you tested. I've just merged the latest from `v2` into this branch, so if you try it again, you should only have a handful of files in the vendor directory. And just to confirm, those are [ruby dependencies](https://github.com/envygeeks/jekyll-docker#caching).

Regarding the `package-lock.json` diff, that one definitely surprised me! But I can see now what caused it—after removing the dependencies, I corrected the package name in a separate commit. I didn't realise the package name gets saved in `package-lock.json`, but apparently it does:

```diff
diff --git a/package-lock.json b/package-lock.json
index d542852..0942b8f 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -1,12 +1,11 @@
 {
-  "name": "es6-boilerplate",
+  "name": "jkan",
   "version": "1.0.0",
   "lockfileVersion": 2,
   "requires": true,
   "packages": {
     "": {
-      "name": "es6-boilerplate",
-      "version": "1.0.0",
+      "name": "jkan",
       "license": "MIT",
       "dependencies": {
         "bootstrap": "^4.3.1",
```

Finally, there should already be two scripts in `package.json`: `build` and `watch`. If you run `npm run watch`, it will watch your JavaScript files for changes and automatically regenerate the bundled file in your `_site` directory. This does _not_ run a development server; you must run `jekyll serve` for that as normal. This requires two terminal windows. We _could_ do something clever and tie those into a single command ([like this](https://github.com/flight-deck/Flightdeck-for-Jekyll-with-ParcelJS/blob/master/package.json)), but there would be a few things to think through there, and I'd suggest that be in a separate PR. In the meantime, the commands are the same as the ones in the [existing documentation](https://github.com/timwis/jkan/wiki/Architecture#development-1), though I appreciate that documentation is a bit outdated now with v2, and it should probably be in source control rather than the wiki.

**Comment by lydiascarf** [comment]
Thanks for the quick update and clear explanation!  :bowing_woman: 
- There are now only 15 files in `vendor`. I'll post a quick PR adding the directory to gitignore if you don't mind!
- Installing deps from npm no longer yields package lock updates
- The bundle updates when I make changes to templates after running `npm run watch` and the changes are visible in the dev server I ran with `docker compose up`; `npm run build` also successfully updates the bundle
- I think it's likely to be more maintainable to just have the development server and watch command running in separate tabs than to try and get fancy with it. I just got confused because I misread the documentation! However, I am typically in favor of version controlled docs for the reason you mentioned

**Review by lydiascarf — APPROVED** [review]
Thanks again!

**Pull request merged**
