### PR TITLE
Custom hero image

### PR DESCRIPTION
**Pull request by lydiascarf**
Facilitate having a custom image in the hero section

image

### CODE REVIEW

**Review by BryanQuigley — APPROVED** [review]
LGTM, except we likely should switch over to JPEG for load performance.

**Comment by BryanQuigley** [comment]
Oh, and this is off Phila, but figured it's better to have a sample upstream.

**Comment by BryanQuigley** [comment]
@timwis as this was already discussed #253 care if I merge things that follow along with that homepage change?

**Comment by timwis** [comment]
This looks so good!! Great addition.

I've got two suggestions:
1. At the moment, the hero looks a bit smushed on mobile. Perhaps we could add a utility class to only show the image on large screens? (I think it's `d-none d-md-block` in bootstrap 5)
2. Do you think we should make it configurable in `_config.yml`? (like the `logo` property) I guess the only advantage would be that admins could turn it off if they don't have/want an image, though maybe that's not necessary.

Lastly, as much as I love Philly, I'd love if we could include a generic, non-city-specific image as the default, to maintain JKAN's ready-out-of-the-box attributes. I suppose that's pretty hard to find with a geospatial visualisation (perhaps if we remove the text labels?), lol. If nothing immediately comes to mind, I'm happy for us to use this one for now, and create an issue asking folk to contribute a more generic default image.

**Comment by lydiascarf** [comment]
@timwis I added the style and it looks good on mobile now! Thanks for the comment. We need to move on to other cards if we're going to get to everything, so it would be great if we could source the default image from the community. Same issue with configuration. I tried making it work with `_config` but for some reason the variable didn't populate in the frontend. Not sure if this was a simple issue I couldn't diagnose in time, but I want to make sure I can get to the other home page improvements, so I'm going to leave it as is if that's alright with you!

**Comment by lydiascarf** [comment]
@timwis nevermind about the config!

**Pull request merged**
